### ISSUE TITLE
make alert if download progress is error

### ISSUE THREAD

**Issue by raeka21** [setsumi/Syosetu-Downloader-plus#12]

**Comment by setsumi** [comment]
Should be doing now.

**Comment by raeka21** [comment]
Will close this till I get the error alert. Syosetu when this app is still ver 13, is kind of buggy? the download just suddenly stop, and I had to re-download multiple times just to get it done, especially series with many chapters.

**Comment by setsumi** [comment]
Yes, this was the behavior, when error happened task just stopped silently, but now i tried to catch and show messages at least.

**Comment by raeka21** [comment]
Yep, thanks for all the works! I got the error alert just now, and while its not perfect, I really appreciate it that the new error alert gives me more information to go by.
