### ISSUE TITLE
make a log (see screenshot for example)

### ISSUE THREAD

**Issue by raeka21** [setsumi/Syosetu-Downloader-plus#13]
![Screenshot (68)](https://user-images.githubusercontent.com/114666600/193317648-af4b3027-20c7-492a-b842-d322accb4853.png)

**Comment by setsumi** [comment]
Not really log, but at least errors should be reporting in log like window.

**Comment by raeka21** [comment]
Well, let's just say there's something equivalent to what I asked then.
