### ISSUE TITLE
option to download

### ISSUE THREAD

**Issue by shirogutama** [setsumi/Syosetu-Downloader-plus#6]
Hi, Can you create option to download chapters in markdown(.md) files? I think it will be more easier to read, don't you?

**Comment by setsumi** [comment]
I tried a couple of html to markdown conversion libraries and results was pretty bad. They can't handle complex html with links and even failing on looking like simple html. In addition markdown itself is not solid format but have different flavors for different software etc. Big mess. I suggest looking for proper third party conversion software fitting your needs.

**Comment by shirogutama** [comment]
Doesn't it just like adding # to the title of each chapter title and volume name then save the output as *.md?(for syosetu Without chapter list).
I did this manually with notepad++, but it will be great if you can add this format as option. thanks for your great job!!
